@host = http://localhost:3000
@todoId = 68345a2624a7a84eebacfae4

### create a todo
POST {{host}}/todos
Content-Type: application/json

{
  "title": "Sample Todo"
}

### get all todos
GET {{host}}/todos
Content-Type: application/json

{}

### update a todo
PUT {{host}}/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated Todo"
}

### delete a todo
DELETE {{host}}/todos/{{todoId}}
Content-Type: application/json

### health
GET {{host}}/health
Content-Type: application/json