### create a todo
@todoId = {{randomInt 1 1000}}

POST http://localhost:4000/todos
Content-Type: application/json

{
  "title": "Sample Todo"
}

### get all todos
GET http://localhost:4000/todos
Content-Type: application/json

{}

### update a todo
PUT http://localhost:4000/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated Todo"
}

### delete a todo
DELETE http://localhost:4000/todos/{{todoId}}
Content-Type: application/json

### health
GET http://localhost:4000/health
Content-Type: application/json